global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'crbt-monitoring-rules.yml'

scrape_configs:
  - job_name: eureka-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8761']

  - job_name: config-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8888']

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: file-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: audit-log-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8084']

  - job_name: payment-gateway-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8085']

  - job_name: credit-wallet-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8086']

  - job_name: crbt-campaign-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8090']

  - job_name: crbt-community-library
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8091']

  - job_name: audio-generation-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8092']

  - job_name: crbt-credit-transaction-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8093']

  - job_name: crbt-core-adapter
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8094']
