spring:
  application:
    name: audio-generation-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USER:configuser}:${CONFIG_SERVER_PASSWORD:configsecret}@${CONFIG_SERVER_HOST:localhost}:8888
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${AUDIO_GEN_DB:audio_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eurekauser}:${EUREKA_PASSWORD:eurekasecret}@${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    com.platform: INFO
